const { Router } = require('express');
const authRoutes = require('../modules/auth/auth.routes');
const userRoutes = require('../modules/users/user.routes');
const adminRoutes = require('../modules/admin/admin.routes');
const programaRoutes = require('../modules/programas/programa.routes');
const fichaRoutes = require('../modules/fichas/ficha.routes');
const matriculaRoutes = require('./matricula.routes');
const asistenciaRoutes = require('../modules/asistencia/asistencia.routes');
const calificacionRoutes = require('../modules/calificaciones/calificacion.routes');
const observacionRoutes = require('./observacion.routes');
const comunicadoRoutes = require('./comunicado.routes');
const notificacionRoutes = require('../modules/notificaciones/notificacion.routes');
const mensajeRoutes = require('./mensaje.routes');
const horarioRoutes = require('../modules/horarios/horario.routes');
const configuracionRoutes = require('./configuracion.routes');
const reportesRoutes = require('./reportes.routes');
const documentosRoutes = require('./documentos.routes');
const aprendizRoutes = require('../modules/aprendiz/aprendiz.routes');
const moduloRoutes = require('../modules/modulos/modulo.routes');
const evidenciaRoutes = require('../modules/evidencias/evidencia.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/admin', adminRoutes);
router.use('/programas', programaRoutes);
router.use('/fichas', fichaRoutes);
router.use('/matriculas', matriculaRoutes);
router.use('/asistencia', asistenciaRoutes);
router.use('/calificaciones', calificacionRoutes);
router.use('/observaciones', observacionRoutes);
router.use('/comunicados', comunicadoRoutes);
router.use('/notificaciones', notificacionRoutes);
router.use('/mensajes', mensajeRoutes);
router.use('/horarios', horarioRoutes);
router.use('/configuracion', configuracionRoutes);
router.use('/reportes', reportesRoutes);
router.use('/documentos', documentosRoutes);
router.use('/aprendiz', aprendizRoutes);
router.use('/modulos', moduloRoutes);
router.use('/evidencias', evidenciaRoutes);

module.exports = router;
